name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you and welcome to Knfun. Feel free to also join us on the knative.slack.com in channel #community'
        pr-message: 'Thank you for your contribution and welcome.  Feel free to also join us on the knative.slack.com in channel #community'
